### ISSUE TITLE
test n

### ISSUE THREAD

**Issue by diegobaxoft** [TangoSoftware/TangoDeltaApi#7]
llega?

**Comment by ulatdsoft** [comment]
Si

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: diegobaxoft ***@***.***>
Sent: Thursday, August 22, 2024 10:43:13 AM
To: TangoSoftware/TangoDeltaApi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TangoSoftware/TangoDeltaApi] test n (Issue #7)


llega?
